baseURL = "https://laurencekohli.github.io/labveilletech/"
DefaultContentLanguage = "fr"
defaultContentLanguageInSubdir = false
languageCode = "fr-ch"
title = "Mon laboratoire de veille"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
pagination.pagerSize = 6
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
pagination = "10"
hideAuthor = false
description="Your can add your website description here."
previewCardImagePlacement = "bottom"

[Params.Author]
  name = "Laurence Kohli"
  website = "https://bento.me/laurence-kohli"
  authorInfo = "C'est en visant la lune que l'on atteint les étoiles."
  authorPostImage = "/img/author-post-img.jpg"

[[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url = "/tags/blog/"
    weight = 2

[[menu.main]]
    name = "A propos"
    url = "/about/"
    weight = 3

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

